galaxy_info:
  role_name: vector_role
  namespace: ivanshkutov
  author: Ivan Shkutov
  description: Ansible role to install and configure Vector
  license: MIT
  min_ansible_version: 2.9

dependencies: []
